# Generated by Django 3.0.3 on 2020-02-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('task_id', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.CharField(max_length=10)),
                ('bam_file', models.FilePathField(path='/files/input')),
                ('annotation_file', models.FilePathField(path='/files/input')),
                ('fasta_file', models.FilePathField(path='/files/input')),
                ('offset_file', models.FilePathField(blank=True, null=True, path='/files/input')),
                ('filter_file', models.FilePathField(blank=True, null=True, path='/files/input')),
                ('include', models.BooleanField()),
                ('min_frag', models.IntegerField()),
                ('max_frag', models.IntegerField()),
                ('three_prime', models.BooleanField()),
                ('overlap', models.IntegerField()),
                ('threshold_avg_reads', models.IntegerField()),
                ('threshold_gene_pct', models.IntegerField()),
                ('threshold_start_codon', models.IntegerField()),
                ('alignment_type', models.CharField(max_length=100)),
                ('get_asite', models.BooleanField()),
            ],
        ),
    ]
